apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phpinfo-helm
spec:
  destination:
    namespace: phpinfo-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - phpinfo-helm/values.yaml
    path: main/helm
    repoURL: https://github.com/sebastian-colomar/phpinfo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
