# docker run -d --entrypoint php --name phpinfo --publish 8080 --user 65534:65534 --volume $PWD/src/index.php:/src/index.php:ro --workdir /src/ docker.io/library/php:alpine -f index.php -S 0.0.0.0:8080
secrets:
  index.php:
    file: ./src/index.php
services:
  phpinfo:
    command:
      - -f
      - index.php
      - -S
      - 0.0.0.0:8080
    secrets:
      - 
        mode: 0400
        source: index.php
        target: /src/index.php
        uid: '65534'
        gid: '65534'
    entrypoint: php
    image: docker.io/library/php:alpine
    ports:
      - 8080
    user: nobody:nobody
    working_dir: /src/
version: "3.9" 
