secrets:
  index.php:
    file: ./src/index.php
services:
  phpinfo:
    command:
      - -f
      - index.php
      - -S
      - localhost:8080
    secrets:
      - 
        mode: 0400
        source: index.php
        target: /src/index.php
        uid: 65534
        gid: 65534
    entrypoint: php
    image: docker.io/library/php:alpine
    ports:
      - 8080
    user: nobody
    working_dir: /src/
version: "3.9" 
