apiVersion: v1
kind: Service
metadata:
  name: {{ include "phpinfo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "phpinfo.selectorLabels" . | nindent 4 }}
