kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: alpine
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: docker.io/academiaonline/alpine:latest
