apiVersion: v1
kind: ReplicationController
metadata:
  name: phpinfo-rc
spec:
  replicas: 2
  selector:
    app: phpinfo-rc
  template:
    metadata:
      labels:
        app: phpinfo-rc
    spec:
      containers:
        - name: phpinfo
          image: 'index.docker.io/library/php:alpine@sha256:ab23b416d86aec450ee7b75727f6bbec272edc2764a1b6fad13bc2823c59bb6b'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 100m
              memory: 100M
          env:
            - name: AUTHOR
              value: Sebastian
          securityContext:
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
          volumeMounts:
            - mountPath: /data/index.php
              subPath: index.php
              name: phpinfo-volume
              readOnly: true
          workingDir: /data/
          args:
            - php
            - -f
            - index.php
            - -S
            - 0.0.0.0:8080
      restartPolicy: Always
      securityContext:
        fsGroup: 65534
      volumes:
        - name: phpinfo-volume
          configMap:
              defaultMode: 0400
              items:
                - key: index.php
                  path: index.php
                  mode: 0400
              name: phpinfo-cm
