#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: PHP Info
    iconClass: icon-php
    openshift.io/display-name: 'PHP Info'
    openshift.io/provider-display-name: 'Sebastian Colomar'
    tags: 'php,phpinfo'
    version: '${APP_VERSION}'
  labels:
    app: phpinfo
    samples.operator.openshift.io/managed: 'true'
  name: phpinfo
message: 'PHP Info is now deployed.'
objects:
  -
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: phpinfo-deploy
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: phpinfo
      template:
        metadata:
          labels:
            app: phpinfo
        spec:
          containers:
          -
            image: secobau/phpinfo:${APP_VERSION}
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 30
            name: phpinfo-container
            ports:
              -
                containerPort: 8080
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 1
            resources:
              limits:
                cpu: '${CPU_LIMIT}'
                memory: '${MEMORY_LIMIT}'
              requests:
                cpu: '${CPU_REQUEST}'
                memory: '${MEMORY_REQUEST}'
  -
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: phpinfo-netpol
    spec:
      podSelector:
        matchLabels:
          app: phpinfo
      ingress:
        -
          ports:
            -
              port: 8080
              protocol: TCP
  -
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        console.alpha.openshift.io/overview-app-route: 'true'
      labels:
        app: phpinfo
      name: phpinfo-route
    spec:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: phpinfo-svc
  -
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: phpinfo
      name: phpinfo-svc
    spec:
      ports:
        -
          port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        app: phpinfo
parameters:
  -
    description: The application version.
    displayName: Application Version
    name: APP_VERSION
    required: true
    value: 'latest'
  -
    description: The amount of CPU each container is limited to use.
    displayName: CPU limit
    name: CPU_LIMIT
    required: true
    value: '0.001'
  -
    description: The amount of CPU to request for each container.
    displayName: CPU request
    name: CPU_REQUEST
    required: true
    value: '0.001'
  -
    description: The amount of memory each container is limited to use.
    displayName: Memory limit
    name: MEMORY_LIMIT
    required: true
    value: 32Mi
  -
    description: The amount of memory required for each container to run.
    displayName: Memory request
    name: MEMORY_REQUEST
    required: true
    value: 16Mi
    
