################################################################################
#      Copyright (C) 2023        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
networks:
  phpinfo:
    internal: true
secrets:
  index.php:
    external: false
    file: phpinfo/docker/src/index.php
services:
  phpinfo:
    command:
    - -f
    - index.php
    - -S
    - 0.0.0.0:8080
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 100M
    entrypoint:
    - php
    expose:
    - "8080"
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      test: php -r "print file_get_contents('http://localhost:8080/');"
      timeout: 1s
    image: academiaonline/phpinfo:latest
    networks:
    - phpinfo
    ports:
    - "30000:8080"
    secrets:
    - source: index.php
      target: /srv/index.php
      uid: "65534"
      gid: "65534"
      mode: 0400
    user: nobody:nogroup
    working_dir: /srv/
version: "3.8"
################################################################################
