################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
name: CI                                                                       #
on:                                                                            #
  push:                                                                        #
    branches:                                                                  #
    - main                                                                     #
jobs:                                                                          #
  host:                                                                          #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: run                                                                #
      run: php -f src/index.php -S 0.0.0.0:8080                                &
    - name: test                                                               #
      run:                                                                     |
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            curl localhost:8080/src/index.php | grep "PHP.*phpinfo()" && break ;
          done                                                                 ;
  docker:                                                                          #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: docker-build                                                                #
      run:                                                                     |
        mkdir --parents build-context/
        docker build --file docker/Dockerfile --tag localhost/library/alpine:php-8.1 build-context/
    - name: docker-run
      run: docker run --detach --name test --volume ${PWD}/src/index.php:/app/index.php:ro --workdir /app/ localhost/library/alpine:php-8.1 php81 -f index.php -S 0.0.0.0:9000
    - name: test                                                               #
      run:                                                                     |
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            docker top test
            docker logs test
            docker stats test --no-stream
            docker inspect test
            docker exec test wget -q -O - localhost:9000/index.php | grep "PHP.*phpinfo()" && break ;
          done                                                                 ;
################################################################################
