################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
name: CI                                                                       #
on:                                                                            #
  push:                                                                        #
    branches:                                                                  #
    - main                                                                     #
jobs:                                                                          #
  host:                                                                          #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: run                                                                #
      run: php -f src/index.php -S 0.0.0.0:8080                                &
    - name: test                                                               #
      run:                                                                     |
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            wget -q -O - localhost:8080/src/index.php | grep "PHP.*phpinfo()" && break ;
          done                                                                 ;
  docker:                                                                          #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: docker-build                                                                #
      run:                                                                     |
        mkdir --parents build-context/
        docker build --file docker/Dockerfile --tag localhost/library/alpine:php-8.1 build-context/
    - name: docker-run
      run: docker run --detach --name test --volume ${PWD}/src/index.php:/app/index.php:ro --workdir /app/ localhost/library/alpine:php-8.1 php81 -f index.php -S 0.0.0.0:9000
    - name: test                                                               #
      run:                                                                     |
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            docker exec test wget -q -O - localhost:9000/index.php | grep "PHP.*phpinfo()" && break ;
          done                                                                 ;
  kubernetes:                                                                  #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: init                                                               #
      run:                                                                     |
        uuid=$( md5sum /etc/hosts | cut -d\  -f1 )                      ;
        git clone --single-branch -b v1.2                                      \
          https://github.com/academiaonline/kubernetes $uuid                   ;
        path=$uuid/bin/cluster/ubuntu18/install-docker-kubelet.sh              ;
        source $path                                                           ;
        path=$uuid/bin/cluster/ubuntu18/install-leader.sh                      ;
        source $path                                                           ;
        master=$( kubectl get node | grep master | awk '{ print $1 }' )        ;
        kubectl taint node $master node-role.kubernetes.io/master:NoSchedule-  ;
        rm -rf $uuid                                                           ;
    - name: apply                                                              #
      run: kubectl apply -f kubernetes/manifests/                                  ;
    - name: test                                                               #
      run:                                                                     |
        set -x                                                                 ;
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            kubectl exec phpinfo-po -- wget -q -O - localhost:8080 | grep "PHP.*phpinfo()" && break
          done                                                                 ;
        kubectl get all
################################################################################
