################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
name: CI                                                                       #
on:                                                                            #
  push:                                                                        #
    branches:                                                                  #
    - main                                                                     #
jobs:                                                                          #
  vm:                                                                          #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: test                                                               #
      run: |                                                                   #
        set -x                                                                 ;
                                                                               #
        php -f src/index.php -S 0.0.0.0:8080
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            curl localhost:8080                                                     \
            |                                                                  \
            grep "PHP.*phpinfo()"                                              \
            &&                                                                 \
            break                                                              ;
          done                                                                 ;
                                                                               #
################################################################################
